
version: 2

models:
  - name: stg_user
    description: "user stagging"
    columns:
      - name: user_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: gender_id
        description: "The foreign key for this table"
        data_tests:
          - unique
          - not_null
      - name: country_id
        description: "The foreign key for this table"
        data_tests:
          - unique
          - not_null

  
