
version: 2

models:
  - name: stg_country
    columns:
      - name: country_id
        description: "Unique identifier for each country"
        data_tests:
          - unique
          - not_null
      - name: country_name
        description: "Name of countries"
        data_tests:
          - not_null

  - name: stg_gender
    columns:
      - name: gender_id
        description: "Unique identifier for each gender"
        data_tests:
          - unique
          - not_null
      - name: gender_name
        description: "Name of gender"
        data_tests:
          - not_null

  - name: stg_user
    columns:
      - name: user_id
        description: "Unique identifier for each user"
        data_tests:
          - unique
          - not_null
      - name: name
        description: "Name of user"
        data_tests:
          - not_null
      - name: age
        description: "Age of user"
        data_tests:
          - not_null
      - name: email
        description: "email of user"
        data_tests:
          - not_null
      - name: gender_id
        description: "Unique identifier for each gender"
        data_tests:
          - not_null
      - name: country_id
        description: "Unique identifier for each country"
        data_tests:
          - not_null

  - name: stg_product
    columns:
      - name: product_id
        description: "Unique identifier for each product"
        data_tests:
          - unique
          - not_null
      - name: tag_id
        description: "Unique identifier for each tag"
        data_tests:
          - not_null

  - name: stg_tags
    columns:
      - name: tag_id
        description: "Unique identifier for each tag"
        data_tests:
          - unique
          - not_null
  
  - name: stg_purchased
    columns:
      - name: purchased_id
        description: "Unique identifier for each purchased"
        data_tests:
          - unique
          - not_null
      